# Generated by Django 4.1.6 on 2023-02-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
