# Generated by Django 4.1.6 on 2023-02-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Лев Толстой', max_length=222),
            preserve_default=False,
        ),
    ]
